// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test2.Data;

#nullable disable

namespace Test2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220609101346_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Test2.Entities.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            FirstName = "Karyna",
                            LastName = "Bartashevich"
                        },
                        new
                        {
                            IdClient = 2,
                            FirstName = "Nastya",
                            LastName = "Babior"
                        },
                        new
                        {
                            IdClient = 3,
                            FirstName = "Hanna",
                            LastName = "Tamkovich"
                        });
                });

            modelBuilder.Entity("Test2.Entities.ClientOrder", b =>
                {
                    b.Property<int>("IdClientOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClientOrder"), 1L, 1);

                    b.Property<int>("ClientIdClient")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeIdEmployee")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdClientOrder");

                    b.HasIndex("ClientIdClient");

                    b.HasIndex("EmployeeIdEmployee");

                    b.ToTable("ClientOrders");

                    b.HasData(
                        new
                        {
                            IdClientOrder = 1,
                            ClientIdClient = 1,
                            Comments = "No problems occured",
                            CompletionDate = new DateTime(2022, 6, 9, 12, 13, 46, 341, DateTimeKind.Local).AddTicks(7480),
                            EmployeeIdEmployee = 1,
                            OrderDate = new DateTime(2022, 6, 8, 12, 13, 46, 341, DateTimeKind.Local).AddTicks(7420)
                        });
                });

            modelBuilder.Entity("Test2.Entities.Confectionery", b =>
                {
                    b.Property<int>("IdConfectionery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfectionery"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerOne")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdConfectionery");

                    b.ToTable("Confectioneries");

                    b.HasData(
                        new
                        {
                            IdConfectionery = 1,
                            Name = "Twix",
                            PricePerOne = 4m
                        },
                        new
                        {
                            IdConfectionery = 2,
                            Name = "Snickers",
                            PricePerOne = 5m
                        },
                        new
                        {
                            IdConfectionery = 3,
                            Name = "Mars",
                            PricePerOne = 4m
                        });
                });

            modelBuilder.Entity("Test2.Entities.ConfectioneryClientOrder", b =>
                {
                    b.Property<int>("IdClientOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdConfectionery")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("ClientOrderIdClientOrder")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConfectioneryIdConfectionery")
                        .HasColumnType("int");

                    b.HasKey("IdClientOrder", "IdConfectionery");

                    b.HasIndex("ClientOrderIdClientOrder");

                    b.HasIndex("ConfectioneryIdConfectionery");

                    b.ToTable("ConfectioneryClientOrders");

                    b.HasData(
                        new
                        {
                            IdClientOrder = 2,
                            IdConfectionery = 2,
                            Amount = 3,
                            Comments = "None"
                        });
                });

            modelBuilder.Entity("Test2.Entities.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmployee");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            IdEmployee = 1,
                            FirstName = "William",
                            LastName = "Shakespeare"
                        },
                        new
                        {
                            IdEmployee = 2,
                            FirstName = "Lizaveta",
                            LastName = "Babior"
                        },
                        new
                        {
                            IdEmployee = 3,
                            FirstName = "Iman",
                            LastName = "Sayyadzadeh"
                        });
                });

            modelBuilder.Entity("Test2.Entities.ClientOrder", b =>
                {
                    b.HasOne("Test2.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientIdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test2.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Test2.Entities.ConfectioneryClientOrder", b =>
                {
                    b.HasOne("Test2.Entities.ClientOrder", null)
                        .WithMany("ConfectioneryClientOrder")
                        .HasForeignKey("ClientOrderIdClientOrder");

                    b.HasOne("Test2.Entities.Confectionery", null)
                        .WithMany("ConfectioneryClientOrder")
                        .HasForeignKey("ConfectioneryIdConfectionery");
                });

            modelBuilder.Entity("Test2.Entities.ClientOrder", b =>
                {
                    b.Navigation("ConfectioneryClientOrder");
                });

            modelBuilder.Entity("Test2.Entities.Confectionery", b =>
                {
                    b.Navigation("ConfectioneryClientOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
